# name of your github action
name: Build Prod
# this will help you specify where to run 
on:
  workflow_dispatch:
  push:
    branches:
    # this will run on the electron branch
      - prod
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: prod
    - uses: actions/setup-node@master
      with:
        node-version: 16.5.0
    - name: install dependencies
      run: npm install
      
    - name: build react
      run: yarn build
      
    - name: build electron
      run: electron-builder -c.extraMetadata.main=build/electron.js
      
    - name: see directory
      run: ls
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
      with:
        ref: feature/github-actions        
    - uses: actions/setup-node@master
      with:
        node-version: 16.5.0
    - name: install dependencies
      run: npm install
    - name: build command
      run: npm run electron:build
    - name: see directory
      run: ls
